# LobbyTools 配置文件
# 作者: KumaKorin

# 基本设置
settings:
  # 启用或禁用防伤害功能
  prevent-damage: true
  # 启用或禁用防饥饿功能
  prevent-hunger: true
  # 启用或禁用防虚空掉落功能
  void-teleport: true
  # 启用或禁用阻止PVP功能
  prevent-pvp: true
  # 启用或禁用阻止破坏方块功能
  prevent-block-break: true
  # 启用或禁用阻止放置方块功能
  prevent-block-place: true
  # 启用或禁用阻止与方块交互功能（箱子、门、信标等）
  prevent-block-interact: true
  # 启用或禁用阻止与门交互功能（所有类型的门、栅栏门、活板门等）
  prevent-door-interaction: true
  # 启用或禁用阻止捡起物品功能
  prevent-item-pickup: true
  # 启用或禁用阻止收获浆果功能
  prevent-harvest: true
  # 启用或禁用命令阻止功能
  prevent-commands: true
  # 启用或禁用阻止TAB补全非白名单命令功能
  prevent-tab-completion: true
  # 启用或禁用加入服务器时显示title
  show-join-title: false

# 出生点设置
# 注意：这部分将由 /lobbytools setspawn 命令自动更新
# 可以手动修改，但建议使用命令
spawn:
  # 出生点所在世界的名称
  world: world
  # 出生点坐标
  x: 0.0
  y: 64.0
  z: 0.0
  # 出生点视角
  yaw: 0.0
  pitch: 0.0

# 命令白名单
# 这些命令可以在没有特定权限的情况下使用
command-whitelist:
  - /spawn
  - /lobby
  - /hub
  - /help

# 标题设置
title:
  # 主标题内容
  main:
    - "<gradient:#7FFFD4:#40E0D0><bold>MIAOMC Network</bold></gradient>"
    - "<blue>你好，冒险家!</blue>"
    - "<green>欢迎回来!</green>"
  # 副标题内容
  sub:
    - "<yellow>祝您游戏愉快!</yellow>"
    - "<white>玩得开心!</white>"
    - "<light_purple>希望你在这里找到乐趣!</light_purple>"
  # 淡入时间(ticks)
  fade-in: 10
  # 停留时间(ticks)
  stay: 70
  # 淡出时间(ticks)
  fade-out: 20

# 消息设置
messages:
  # 当玩家没有权限使用命令时显示的消息
  no-command-permission: "&c你没有权限使用命令!"
  # 当玩家设置出生点成功时显示的消息
  spawn-set: "&a出生点已成功设置到你当前的位置!"
  # 当玩家传送到出生点时显示的消息
  teleport-to-spawn: "&a你已被传送到出生点!"
  # 当插件配置重新加载时显示的消息
  config-reloaded: "&aLobbyTools 配置已重新加载!"
